/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./index.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        surface: "hsl(var(--card))",
        text: "hsl(var(--foreground))",
        mutedText: "hsl(var(--muted-foreground))",
        border: "hsl(var(--border))",
        accent: "hsl(var(--accent))",
        accentDark: "#c0630b",
        danger: "hsl(var(--destructive))",
        success: "hsl(var(--success))",
        gold: "hsl(var(--gold))",
        navy: "hsl(var(--navy))",
        parchment: "hsl(var(--parchment))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      fontFamily: {
        heading: ["SpaceGrotesk-Bold"],
        body: ["SpaceGrotesk-Regular"],
        game: ["PixelifySans-Regular"],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "40px",
      },
      borderRadius: {
        none: "0px",
        xs: "calc(var(--radius) * 0.5)",
        sm: "calc(var(--radius) * 0.75)",
        md: "calc(var(--radius) * 1)",
        lg: "calc(var(--radius) * 1.5)",
        pill: "999px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
